# Generated by Django 5.1.1 on 2024-10-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcontentmaker',
            name='cover',
            field=models.ImageField(upload_to='pod_covers/'),
        ),
        migrations.AlterField(
            model_name='testcontentmaker',
            name='creator',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testcontentmaker',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='testcontentmaker',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
