# Generated by Django 5.1.1 on 2024-10-06 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='info_status',
            field=models.CharField(blank=True, choices=[('cm', 'Completed'), ('nc', 'Not Completed'), ('ip', 'In Progress')], default='nc', max_length=3, null=True, verbose_name='User Status'),
        ),
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('cover', models.ImageField(upload_to='BO/covers/', verbose_name='BO Profile Cover')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('datetime_created', models.DateField(auto_now_add=True, verbose_name='Datetime of Creation')),
                ('status', models.CharField(blank=True, choices=[('ap', 'Approved'), ('rj', 'Rejected'), ('ip', 'In Progress')], default='ip', max_length=3, null=True, verbose_name='CM Status')),
                ('field', models.CharField(blank=True, choices=[('app', 'Agriculture, Plants, and Pets'), ('abs', 'Architecture and Building Services'), ('cam', 'Consulting and Management'), ('cnp', 'Content Production'), ('des', 'Design'), ('dts', 'Digital and Technology Services'), ('edu', 'Education'), ('ens', 'Engineering Services'), ('fac', 'Fashion and Clothing'), ('caf', 'Commercial and Financial'), ('fic', 'Food Industry and Cooking'), ('haa', 'Handicrafts and Arts'), ('hmb', 'Health, Medicine, and Beauty'), ('hbb', 'Home-based Business'), ('iat', 'Investment and Trading'), ('mai', 'Manufacturing and Industrial'), ('maa', 'Marketing and Advertising'), ('npc', 'Non-Profit and Charity'), ('obs', 'Online Business and Store'), ('tai', 'Tourism and Immigration')], max_length=3, null=True, verbose_name='CM Field')),
                ('link1', models.CharField(max_length=200, verbose_name='Link1')),
                ('link2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link2')),
                ('email', models.CharField(blank=True, max_length=300, null=True, verbose_name='Email')),
                ('activity_years', models.CharField(blank=True, choices=[('lt1', 'Less Than 1 Years'), ('1yrs', '1 Year'), ('2yrs', '2 Years'), ('3yrs', '3 Years'), ('4yrs', '4 Years'), ('5yrs', '5 Years'), ('510', '5 - 10 Years'), ('m10', 'More Than 10 Years')], max_length=4, null=True, verbose_name='Activity Years')),
                ('sponsor_experience', models.CharField(blank=True, choices=[('hve', 'Have'), ('dnt', "Don't Have")], max_length=3, null=True, verbose_name='Sponsor Experience')),
                ('general_proposal', models.FileField(blank=True, null=True, upload_to='BO/general_proposals/', verbose_name='General Proposal')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-datetime_created',),
            },
        ),
        migrations.CreateModel(
            name='ContentMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('creator', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creator')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('cover', models.ImageField(upload_to='CM/covers/', verbose_name='CM Profile Cover')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('datetime_created', models.DateField(auto_now_add=True, verbose_name='Datetime of Creation')),
                ('status', models.CharField(blank=True, choices=[('ap', 'Approved'), ('rj', 'Rejected'), ('ip', 'In Progress')], default='ip', max_length=3, null=True, verbose_name='CM Status')),
                ('platform', models.CharField(blank=True, choices=[('pd', 'Podcaster'), ('in', 'Instagram'), ('yt', 'Youtube'), ('ap', 'Aparat')], max_length=3, null=True, verbose_name='CM Platform')),
                ('field', models.CharField(blank=True, choices=[('art', 'Art'), ('b&s', 'Business & Startups'), ('c&t', 'Cinema & TV'), ('com', 'Comedy'), ('c&s', 'Culture & Social'), ('edu', 'Education'), ('e&s', 'Entertainment & Story'), ('hlf', 'Health, Life Style & Fashion'), ('his', 'History'), ('mus', 'Music'), ('pol', 'Politics'), ('rel', 'Religions'), ('sdv', 'Self Development'), ('spo', 'Sport'), ('t&s', 'Technology & Science'), ('trc', 'True Crime')], max_length=3, null=True, verbose_name='CM Field')),
                ('link1', models.CharField(max_length=200, verbose_name='Link1')),
                ('link2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link2')),
                ('link3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link3')),
                ('link4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link4')),
                ('id1', models.CharField(max_length=200, verbose_name='ID1')),
                ('id2', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID2')),
                ('id3', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID3')),
                ('id4', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID4')),
                ('email', models.CharField(blank=True, max_length=300, null=True, verbose_name='Email')),
                ('min_price', models.PositiveIntegerField(verbose_name='Min Price')),
                ('max_price', models.PositiveIntegerField(verbose_name='Max Price')),
                ('activity_years', models.CharField(blank=True, choices=[('lt1', 'Less Than 1 Years'), ('1yrs', '1 Year'), ('2yrs', '2 Years'), ('3yrs', '3 Years'), ('4yrs', '4 Years'), ('5yrs', '5 Years'), ('510', '5 - 10 Years'), ('m10', 'More Than 10 Years')], max_length=4, null=True, verbose_name='Activity Years')),
                ('played', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Played (Viewed)')),
                ('subscribers', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Subscribers (Followers)')),
                ('sponsee_experience', models.CharField(blank=True, choices=[('hve', 'Have'), ('dnt', "Don't Have")], max_length=3, null=True, verbose_name='Sponsee Experience')),
                ('ready', models.CharField(blank=True, choices=[('is', 'Is'), ('nt', "Isn't")], max_length=3, null=True, verbose_name='Ready to Receive Requests')),
                ('general_proposal', models.FileField(blank=True, null=True, upload_to='CM/general_proposals/', verbose_name='General Proposal')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-datetime_created',),
            },
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('unique_url_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('datetime_created', models.DateField(auto_now_add=True, verbose_name='Datetime of Creation')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('status', models.CharField(choices=[('wa', 'Waiting'), ('rj', 'Rejected'), ('ip', 'Open'), ('as', 'Assigned'), ('pa', 'Paid')], default='wa', max_length=3, verbose_name='Sponsorship Status')),
                ('type', models.CharField(choices=[('nsr', 'Need Sponsor'), ('nse', 'Need Sponsee')], max_length=3, verbose_name='Sponsorship Type')),
                ('min_price', models.PositiveIntegerField(verbose_name='Min Price')),
                ('max_price', models.PositiveIntegerField(verbose_name='Max Price')),
                ('specialized_cm_proposal', models.FileField(blank=True, null=True, upload_to='sponsorships/specialized_cm_proposals/', verbose_name='Specialized CM Proposal')),
                ('specialized_bo_proposal', models.FileField(blank=True, null=True, upload_to='sponsorships/specialized_bo_proposals/', verbose_name='Specialized BO Proposal')),
                ('sponsor_sign', models.CharField(choices=[('dne', 'Done'), ('ndn', 'Not Done')], default='ndn', max_length=3, verbose_name='Sponsor Sign')),
                ('sponsee_sign', models.CharField(choices=[('dne', 'Done'), ('ndn', 'Not Done')], default='ndn', max_length=3, verbose_name='Sponsee Sign')),
                ('favorite_cm_field1', models.CharField(choices=[('nom', 'No Matter'), ('art', 'Art'), ('b&s', 'Business & Startups'), ('c&t', 'Cinema & TV'), ('com', 'Comedy'), ('c&s', 'Culture & Social'), ('edu', 'Education'), ('e&s', 'Entertainment & Story'), ('hlf', 'Health, Life Style & Fashion'), ('his', 'History'), ('mus', 'Music'), ('pol', 'Politics'), ('rel', 'Religions'), ('sdv', 'Self Development'), ('spo', 'Sport'), ('t&s', 'Technology & Science'), ('trc', 'True Crime')], default='nom', max_length=3, verbose_name='Favorite CM Field 1')),
                ('favorite_cm_field2', models.CharField(blank=True, choices=[('nom', 'No Matter'), ('art', 'Art'), ('b&s', 'Business & Startups'), ('c&t', 'Cinema & TV'), ('com', 'Comedy'), ('c&s', 'Culture & Social'), ('edu', 'Education'), ('e&s', 'Entertainment & Story'), ('hlf', 'Health, Life Style & Fashion'), ('his', 'History'), ('mus', 'Music'), ('pol', 'Politics'), ('rel', 'Religions'), ('sdv', 'Self Development'), ('spo', 'Sport'), ('t&s', 'Technology & Science'), ('trc', 'True Crime')], max_length=3, null=True, verbose_name='Favorite CM Field 2')),
                ('favorite_cm_field3', models.CharField(blank=True, choices=[('nom', 'No Matter'), ('art', 'Art'), ('b&s', 'Business & Startups'), ('c&t', 'Cinema & TV'), ('com', 'Comedy'), ('c&s', 'Culture & Social'), ('edu', 'Education'), ('e&s', 'Entertainment & Story'), ('hlf', 'Health, Life Style & Fashion'), ('his', 'History'), ('mus', 'Music'), ('pol', 'Politics'), ('rel', 'Religions'), ('sdv', 'Self Development'), ('spo', 'Sport'), ('t&s', 'Technology & Science'), ('trc', 'True Crime')], max_length=3, null=True, verbose_name='Favorite CM Field 3')),
                ('favorite_bo_field1', models.CharField(choices=[('nom', 'No Matter'), ('app', 'Agriculture, Plants, and Pets'), ('abs', 'Architecture and Building Services'), ('cam', 'Consulting and Management'), ('cnp', 'Content Production'), ('des', 'Design'), ('dts', 'Digital and Technology Services'), ('edu', 'Education'), ('ens', 'Engineering Services'), ('fac', 'Fashion and Clothing'), ('caf', 'Commercial and Financial'), ('fic', 'Food Industry and Cooking'), ('haa', 'Handicrafts and Arts'), ('hmb', 'Health, Medicine, and Beauty'), ('hbb', 'Home-based Business'), ('iat', 'Investment and Trading'), ('mai', 'Manufacturing and Industrial'), ('maa', 'Marketing and Advertising'), ('npc', 'Non-Profit and Charity'), ('obs', 'Online Business and Store'), ('tai', 'Tourism and Immigration')], default='nom', max_length=3, verbose_name='Favorite BO Field 1')),
                ('favorite_bo_field2', models.CharField(blank=True, choices=[('nom', 'No Matter'), ('app', 'Agriculture, Plants, and Pets'), ('abs', 'Architecture and Building Services'), ('cam', 'Consulting and Management'), ('cnp', 'Content Production'), ('des', 'Design'), ('dts', 'Digital and Technology Services'), ('edu', 'Education'), ('ens', 'Engineering Services'), ('fac', 'Fashion and Clothing'), ('caf', 'Commercial and Financial'), ('fic', 'Food Industry and Cooking'), ('haa', 'Handicrafts and Arts'), ('hmb', 'Health, Medicine, and Beauty'), ('hbb', 'Home-based Business'), ('iat', 'Investment and Trading'), ('mai', 'Manufacturing and Industrial'), ('maa', 'Marketing and Advertising'), ('npc', 'Non-Profit and Charity'), ('obs', 'Online Business and Store'), ('tai', 'Tourism and Immigration')], max_length=3, null=True, verbose_name='Favorite BO Field 2')),
                ('favorite_bo_field3', models.CharField(blank=True, choices=[('nom', 'No Matter'), ('app', 'Agriculture, Plants, and Pets'), ('abs', 'Architecture and Building Services'), ('cam', 'Consulting and Management'), ('cnp', 'Content Production'), ('des', 'Design'), ('dts', 'Digital and Technology Services'), ('edu', 'Education'), ('ens', 'Engineering Services'), ('fac', 'Fashion and Clothing'), ('caf', 'Commercial and Financial'), ('fic', 'Food Industry and Cooking'), ('haa', 'Handicrafts and Arts'), ('hmb', 'Health, Medicine, and Beauty'), ('hbb', 'Home-based Business'), ('iat', 'Investment and Trading'), ('mai', 'Manufacturing and Industrial'), ('maa', 'Marketing and Advertising'), ('npc', 'Non-Profit and Charity'), ('obs', 'Online Business and Store'), ('tai', 'Tourism and Immigration')], max_length=3, null=True, verbose_name='Favorite BO Field 3')),
                ('sponsee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships_sponsee', to=settings.AUTH_USER_MODEL)),
                ('sponsee_invitation1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_sponsee1', to='sponsorships.contentmaker')),
                ('sponsee_invitation2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_sponsee2', to='sponsorships.contentmaker')),
                ('sponsee_invitation3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_sponsee3', to='sponsorships.contentmaker')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships_sponsor', to=settings.AUTH_USER_MODEL)),
                ('sponsor_invitation1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_sponsor1', to='sponsorships.businessowner')),
                ('sponsor_invitation2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_sponsor2', to='sponsorships.businessowner')),
                ('sponsor_invitation3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_sponsor3', to='sponsorships.businessowner')),
            ],
            options={
                'ordering': ('-datetime_created',),
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('datetime_created', models.DateField(auto_now_add=True, verbose_name='Datetime of Creation')),
                ('roughly_price', models.PositiveIntegerField(verbose_name='Roughly Offering Price')),
                ('proposal', models.FileField(blank=True, null=True, upload_to='offers/proposals/', verbose_name='Offering Proposal')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesters', to=settings.AUTH_USER_MODEL, verbose_name='Requester')),
                ('sponsorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='sponsorships.sponsorship', verbose_name='Sponsorship')),
            ],
            options={
                'ordering': ('-datetime_created',),
            },
        ),
    ]
