# Generated by Django 5.1.1 on 2024-10-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0002_alter_customusermodel_info_status_businessowner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(blank=True, choices=[('su', 'Submitted'), ('rj', 'Rejected'), ('ac', 'Accepted')], default='su', max_length=3, null=True, verbose_name='Offer Status'),
        ),
    ]
