# Generated by Django 5.1.1 on 2024-10-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0003_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmaker',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='National Code'),
        ),
    ]
