# Generated by Django 5.1.1 on 2024-10-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0004_contentmaker_national_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmaker',
            name='max_price',
        ),
    ]
