# Generated by Django 5.1.1 on 2024-10-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0006_alter_businessowner_general_proposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner',
            name='link1',
            field=models.URLField(verbose_name='Link1'),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='link2',
            field=models.URLField(blank=True, null=True, verbose_name='Link2'),
        ),
        migrations.AlterField(
            model_name='contentmaker',
            name='link1',
            field=models.URLField(verbose_name='Link1'),
        ),
        migrations.AlterField(
            model_name='contentmaker',
            name='link2',
            field=models.URLField(blank=True, null=True, verbose_name='Link2'),
        ),
        migrations.AlterField(
            model_name='contentmaker',
            name='link3',
            field=models.URLField(blank=True, null=True, verbose_name='Link3'),
        ),
        migrations.AlterField(
            model_name='contentmaker',
            name='link4',
            field=models.URLField(blank=True, null=True, verbose_name='Link4'),
        ),
    ]
