# Generated by Django 5.1.1 on 2024-10-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0007_alter_businessowner_link1_alter_businessowner_link2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessowner',
            name='activity_years',
        ),
        migrations.AddField(
            model_name='businessowner',
            name='year',
            field=models.CharField(blank=True, choices=[('lt1', 'Less Than 1 Years'), ('1yrs', '1 Year'), ('2yrs', '2 Years'), ('3yrs', '3 Years'), ('4yrs', '4 Years'), ('5yrs', '5 Years'), ('510', '5 - 10 Years'), ('m10', 'More Than 10 Years')], max_length=4, null=True, verbose_name='Foundation Year'),
        ),
    ]
