# Generated by Django 5.1.1 on 2024-10-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0008_remove_businessowner_activity_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='type',
        ),
    ]
