# Generated by Django 5.1.1 on 2024-10-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0009_remove_customusermodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner',
            name='field',
            field=models.CharField(blank=True, choices=[('app', 'Agriculture, Plants, and Pets'), ('abs', 'Architecture and Building Services'), ('cam', 'Consulting and Management'), ('cnp', 'Content Production'), ('des', 'Design'), ('dts', 'Digital and Technology Services'), ('edu', 'Education'), ('ens', 'Engineering Services'), ('fac', 'Fashion and Clothing'), ('caf', 'Commercial and Financial'), ('fic', 'Food Industry and Cooking'), ('haa', 'Handicrafts and Arts'), ('hmb', 'Health, Medicine, and Beauty'), ('hbb', 'Home-based Business'), ('iat', 'Investment and Trading'), ('mai', 'Manufacturing and Industrial'), ('maa', 'Marketing and Advertising'), ('npc', 'Non-Profit and Charity'), ('obs', 'Online Business and Store'), ('tai', 'Tourism and Immigration')], max_length=3, null=True, verbose_name='BO Field'),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='status',
            field=models.CharField(blank=True, choices=[('ap', 'Approved'), ('rj', 'Rejected'), ('ip', 'In Progress')], default='ip', max_length=3, null=True, verbose_name='BO Status'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='info_status',
            field=models.CharField(blank=True, choices=[('cm', 'Content Maker'), ('bo', 'Business Owner'), ('du', 'Dual - Both'), ('nc', 'Not Completed'), ('ip', 'In Progress')], default='nc', max_length=3, null=True, verbose_name='User Status'),
        ),
    ]
